### ISSUE TITLE
Why scrape the IONOS website, when DDNS supported natively?

### ISSUE THREAD

**Issue by pawel-kow** [hoppler/IonosApiPhp#1]
Hi,

IONOS supports DynDNS with an open protocol Domain Connect:
https://www.ionos.com/help/domains/configuring-your-ip-address/connecting-a-domain-to-a-network-with-a-changing-ip-using-dynamic-dns-linux/

There is a ready python client in open source.
If Php is needed, then it's easy to write a client using specification on https://www.domainconnect.org/

**Comment by hoppler** [comment]
Hi,

thx for the information. While i was programming this the API was not available or i havent found it then.

**Comment by mundinbass** [comment]
This isn't true for all services. In order to use their DDNS you must be paying for a server package, otherwise it locks you out.

**Comment by hoppler** [comment]
good to know. now im less motivated to adapt to the ddns api^^

------ Originalnachricht ------
Von: "mundinbass" <notifications@github.com<mailto:notifications@github.com>>
An: "hoppler/IonosApiPhp" <IonosApiPhp@noreply.github.com<mailto:IonosApiPhp@noreply.github.com>>
Cc: "hoppler" <michael.ofenloch@outlook.com<mailto:michael.ofenloch@outlook.com>>; "Comment" <comment@noreply.github.com<mailto:comment@noreply.github.com>>
Gesendet: 20.02.2020 19:26:38
Betreff: Re: [hoppler/IonosApiPhp] Why scrape the IONOS website, when DDNS supported natively? (#1)


This isn't true for all services. In order to use their DDNS you must be paying for a server package, otherwise it locks you out.

**Comment by pawel-kow** [comment]
> This isn't true for all services. In order to use their DDNS you must be paying for a server package, otherwise it locks you out.

Not true. This API is open and available in every package.

**Comment by hoppler** [comment]
Hi,

in germany its possible to use the api, but if you execute the php code directly on the 1und1 server, you have to provide the ip of the domain api.domainconnect.1and1.com because it cannot be resolved on it.

**Comment by pawel-kow** [comment]
@hoppler interesting! I would love to know the details. Domain Connect is widely used on IONOS servers which use Plesk and their Domain Connect integration.

Please open an issue at https://github.com/Domain-Connect/DomainConnectDDNS-Python with the error output or mail on the address domain_connect_admin@domain.ionos.com with the details. I'd love to help tracing the real problem.

**Comment by hoppler** [comment]
@pawel-kow i sent you an email but ill add its content here too

To reproduce it, you can curl for example "https://api.domainconnect.1and1.com/v2/1und1.de/settings" from a german 1and1 server which returned a "Curl (6) Could not resolve host" for me. 

To fix it on my end, i had to set the CURLOPT_RESOLVE option with: "exampleHost.de:443:212.227.15.247" where 212.227.15.247 is the IP api.domainconnect.1and1.com resolves to.

Here is an example code with file_get_contents which returns: "file_get_contents(): php_network_getaddresses: getaddrinfo failed: Name or service not known"

```php
<?php
$url = 'https://api.domainconnect.1and1.com/v2/1und1.de/settings';

set_error_handler(
    function ($severity, $message, $file, $line) {
        throw new ErrorException($message, $severity, $severity, $file, $line);
    }
);

try {
    echo file_get_contents($url);
}
catch (Exception $e) {
    echo $e->getMessage();
}

restore_error_handler();
```

**Comment by pawel-kow** [comment]
Issue fixed now:
```
~$ curl "https://api.domainconnect.1and1.com/v2/1und1.de/settings"
{"market":"us","urlSyncUX":"https://domainconnect.1and1.com/sync","urlAPI":"https://api.domainconnect.1and1.com","urlAsyncUX":"https://domainconnect.1and1.com/async","width":"800","providerName":"1and1","height":"750"}
```

**Comment by hoppler** [comment]
@pawel-kow tried it and it works now on german servers too. thx for that^^
